### ISSUE TITLE
what is the return value of implicit function for?

### ISSUE THREAD

**Issue by se8820726** [Q-Minh/naive-surface-nets#1]
hi
thanks for your efforts on making and implementing this algorithm. 
the implicit function gets 3 values which are the coordinates of a 3d space and return an scalar value. 
what is the scalar value, i don't get it. what does it demonstrate?

**Comment by Q-Minh** [comment]
In most cases, the scalar value represents a signed distance to the surface. Usually, a scalar value of 0 returned from the implicit function means that the (x,y,z) coordinates given to the implicit function lie exactly on the surface. In other words, the given (x,y,z) coordinates were evaluated by the function to be at a distance of 0 to the surface (so exactly on the surface). If the returned value was 10 for a given (x,y,z) point, then it would mean that that point was at a distance of 10 from the exterior of the surface. If the returned value was -10, then it would mean that that point was at a distance of 10 from the interior of the surface. You can also take exterior to be negative distances and interior to be positive distances, as long as they are opposite.

In a more general case, the scalar value could mean anything, like temperature, for example. If you wanted to visualize the isosurface of a temperature distribution in space where the temperature = 10 degrees, then you would want to extract the isosurface with an isovalue of 10. In that case, the scalar value returned by the implicit function represents the temperature at a given (x,y,z) point. Then a scalar value of 10 returned from the implicit function at an (x,y,z) point would indicate that that point is exactly on the surface.

So the implicit function simply returns a scalar value for any (x,y,z) point in space, and whenever that scalar value is equal to the isovalue (which is specified by the user), then it demonstrates that the point (x,y,z) lies exactly on the surface.

Let me know if this answered your question adequately.
